# Generated by Django 4.2.7 on 2025-11-04 02:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

CREACION = 'Fecha de creación',
ACTUALIZACION = 'Fecha de actualización',
ELIMINACION = 'Fecha de eliminación'

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=CREACION)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=ACTUALIZACION)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name=ELIMINACION)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=CREACION)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=ACTUALIZACION)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name=ELIMINACION)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='mascotas.especie')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'razas',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'especie')},
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=CREACION)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=ACTUALIZACION)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name=ELIMINACION)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='usuarios.cliente')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='mascotas.especie')),
                ('raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='mascotas.raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name=CREACION)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=ACTUALIZACION)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name=ELIMINACION)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'db_table': 'historias_clinicas',
            },
        ),
    ]
