# Generated by Django 5.2.7 on 2025-11-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_especie_created_at_alter_especie_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
