# Generated by Django 5.2.7 on 2025-11-21 05:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0002_alter_categoria_color_alter_kardex_detalle_and_more"),
        ("mascotas", "0001_initial"),
        ("usuarios", "0002_resetpasswordtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_consulta",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de consulta",
                    ),
                ),
                (
                    "descripcion_consulta",
                    models.TextField(verbose_name="Descripción de la consulta"),
                ),
                ("diagnostico", models.TextField(verbose_name="Diagnóstico")),
                (
                    "notas_adicionales",
                    models.TextField(
                        blank=True, default="", verbose_name="Notas adicionales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "consentimiento_token",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Token de Consentimiento",
                    ),
                ),
                (
                    "consentimiento_otorgado",
                    models.BooleanField(
                        default=False, verbose_name="Consentimiento Otorgado"
                    ),
                ),
                (
                    "consentimiento_fecha",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Consentimiento"
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_atendidas",
                        to="usuarios.veterinario",
                        verbose_name="Veterinario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-fecha_consulta"],
            },
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_examen",
                    models.CharField(
                        choices=[
                            ("HEMOGRAMA", "Hemograma completo"),
                            ("QUIMICA_SANGUINEA", "Química sanguínea"),
                            ("URINALISIS", "Urianálisis"),
                            ("COPROLOGICO", "Coprológico"),
                            ("RAYOS_X", "Rayos X"),
                            ("ECOGRAFIA", "Ecografía"),
                            ("CITOLOGIA", "Citología"),
                            ("BIOPSIA", "Biopsia"),
                            ("ELECTROCARDIOGRAMA", "Electrocardiograma"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de examen",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción adicional"
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de orden"
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examenes",
                        to="consultas.consulta",
                        verbose_name="Consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Exámenes",
                "ordering": ["tipo_examen"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Fecha de creación de la historia",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "estado_vacunacion_actual",
                    models.CharField(
                        choices=[
                            ("AL_DIA", "Al día"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("NINGUNA", "Ninguna"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Estado de vacunación actual",
                    ),
                ),
                (
                    "mascota",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historias_consulta",
                        to="mascotas.mascota",
                        verbose_name="Mascota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "ordering": ["-fecha_actualizacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AL_DIA", "Al día"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("NINGUNA", "Ninguna"),
                        ],
                        max_length=20,
                        verbose_name="Estado de vacunación",
                    ),
                ),
                (
                    "vacunas_descripcion",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Vacunas pendientes/aplicadas",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de registro",
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacunas",
                        to="consultas.consulta",
                        verbose_name="Consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Vacuna",
                "verbose_name_plural": "Historial de Vacunas",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Prescripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True, default="", verbose_name="Indicaciones de uso"
                    ),
                ),
                (
                    "fecha_prescripcion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de prescripción",
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescripciones",
                        to="consultas.consulta",
                        verbose_name="Consulta",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescripciones",
                        to="inventario.producto",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción",
                "verbose_name_plural": "Prescripciones",
                "ordering": ["fecha_prescripcion"],
            },
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["-fecha_consulta"], name="consultas_c_fecha_c_c19ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["veterinario"], name="consultas_c_veterin_929b6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["mascota"], name="consultas_c_mascota_d1f96d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examen",
            index=models.Index(
                fields=["tipo_examen"], name="consultas_e_tipo_ex_267954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiaclinica",
            index=models.Index(
                fields=["mascota"], name="consultas_h_mascota_f49683_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiaclinica",
            index=models.Index(
                fields=["-fecha_actualizacion"], name="consultas_h_fecha_a_747a28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialvacuna",
            index=models.Index(
                fields=["-fecha_registro"], name="consultas_h_fecha_r_2c65e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialvacuna",
            index=models.Index(fields=["estado"], name="consultas_h_estado_18fa04_idx"),
        ),
        migrations.AddIndex(
            model_name="prescripcion",
            index=models.Index(
                fields=["medicamento"], name="consultas_p_medicam_3fc8de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescripcion",
            index=models.Index(
                fields=["-fecha_prescripcion"], name="consultas_p_fecha_p_71895e_idx"
            ),
        ),
    ]
