# Generated by Django 4.2.7 on 2025-11-04 02:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

CONSULTA= 'consultas.consulta'
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mascotas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de consulta')),
                ('descripcion_consulta', models.TextField(help_text='Síntomas, observaciones, motivo de consulta.', verbose_name='Descripción de la consulta')),
                ('diagnostico', models.TextField(help_text='Diagnóstico clínico del veterinario.', verbose_name='Diagnóstico')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Recomendaciones o seguimiento', null=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('mascota', models.ForeignKey(help_text='Mascota que recibe la consulta.', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades a suministrar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('indicaciones', models.TextField(blank=True, help_text='Ej: Tomar 1 tableta cada 8 horas durante 7 días', null=True, verbose_name='Indicaciones de uso')),
                ('fecha_prescripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de prescripción')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to=CONSULTA, verbose_name='Consulta')),
                ('medicamento', models.ForeignKey(help_text='Medicamento del inventario a prescribir', on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='inventario.producto', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'ordering': ['fecha_prescripcion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], help_text='Estado actual de las vacunas de la mascota', max_length=20, verbose_name='Estado de vacunación')),
                ('vacunas_descripcion', models.TextField(blank=True, help_text='Ej: Rabia, Parvovirus, Moquillo. Campo obligatorio si estado != AL_DIA', null=True, verbose_name='Vacunas pendientes/aplicadas')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('consulta', models.ForeignKey(help_text='Consulta en la que se registró este estado de vacunación', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to=CONSULTA, verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Historial de Vacuna',
                'verbose_name_plural': 'Historial de Vacunas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la historia')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado_vacunacion_actual', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], default='PENDIENTE', help_text='Se actualiza automáticamente con cada consulta', max_length=20, verbose_name='Estado de vacunación actual')),
                ('mascota', models.OneToOneField(help_text='Cada mascota tiene una única historia clínica.', on_delete=django.db.models.deletion.CASCADE, related_name='historias_consulta', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('HEMOGRAMA', 'Hemograma completo'), ('QUIMICA_SANGUINEA', 'Química sanguínea'), ('URINALISIS', 'Urianálisis'), ('COPROLOGICO', 'Coprológico'), ('RAYOS_X', 'Rayos X'), ('ECOGRAFIA', 'Ecografía'), ('CITOLOGIA', 'Citología'), ('BIOPSIA', 'Biopsia'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de examen')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles específicos del examen a realizar', null=True, verbose_name='Descripción adicional')),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de orden')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to=CONSULTA, verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['tipo_examen'],
            },
        ),
    ]
