# Generated by Django 4.2.7 on 2025-11-03 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_remove_kardex_anulado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(default='Perro', max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(default='Criollo', max_length=50, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(default=2, verbose_name='Edad (años)')),
                ('estado_vacunacion', models.CharField(default='AL_DIA', max_length=20, verbose_name='Estado de vacunación')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_mock', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota (Prueba)',
                'verbose_name_plural': 'Mascotas (Pruebas)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de consulta')),
                ('descripcion_consulta', models.TextField(help_text='Síntomas, observaciones, motivo de consulta.', verbose_name='Descripción de la consulta')),
                ('diagnostico', models.TextField(help_text='Diagnóstico clínico del veterinario.', verbose_name='Diagnóstico')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Recomendaciones o seguimiento', null=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('mascota', models.ForeignKey(help_text='Mascota que recibe la consulta.', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consultas.mascotamock', verbose_name='Mascota')),
                ('veterinario', models.ForeignKey(help_text='Veterinario que atiende la consulta', limit_choices_to={'groups__name': 'Veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades a suministrar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('indicaciones', models.TextField(blank=True, help_text='Ej: Tomar 1 tableta cada 8 horas durante 7 días', null=True, verbose_name='Indicaciones de uso')),
                ('fecha_prescripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de prescripción')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='consultas.consulta', verbose_name='Consulta')),
                ('medicamento', models.ForeignKey(help_text='Medicamento del inventario a prescribir', on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='inventario.producto', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'ordering': ['fecha_prescripcion'],
                'indexes': [models.Index(fields=['medicamento'], name='consultas_p_medicam_3fc8de_idx'), models.Index(fields=['-fecha_prescripcion'], name='consultas_p_fecha_p_71895e_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], help_text='Estado actual de las vacunas de la mascota', max_length=20, verbose_name='Estado de vacunación')),
                ('vacunas_descripcion', models.TextField(blank=True, help_text='Ej: Rabia, Parvovirus, Moquillo. Campo obligatorio si estado != AL_DIA', null=True, verbose_name='Vacunas pendientes/aplicadas')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('consulta', models.ForeignKey(help_text='Consulta en la que se registró este estado de vacunación', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='consultas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Historial de Vacuna',
                'verbose_name_plural': 'Historial de Vacunas',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_registro'], name='consultas_h_fecha_r_2c65e0_idx'), models.Index(fields=['estado'], name='consultas_h_estado_18fa04_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la historia')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado_vacunacion_actual', models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], default='PENDIENTE', help_text='Se actualiza automáticamente con cada consulta', max_length=20, verbose_name='Estado de vacunación actual')),
                ('mascota', models.OneToOneField(help_text='Cada mascota tiene una única historia clínica.', on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='consultas.mascotamock', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_actualizacion'],
                'indexes': [models.Index(fields=['mascota'], name='consultas_h_mascota_f49683_idx'), models.Index(fields=['-fecha_actualizacion'], name='consultas_h_fecha_a_747a28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('HEMOGRAMA', 'Hemograma completo'), ('QUIMICA_SANGUINEA', 'Química sanguínea'), ('URINALISIS', 'Urianálisis'), ('COPROLOGICO', 'Coprológico'), ('RAYOS_X', 'Rayos X'), ('ECOGRAFIA', 'Ecografía'), ('CITOLOGIA', 'Citología'), ('BIOPSIA', 'Biopsia'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de examen')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles específicos del examen a realizar', null=True, verbose_name='Descripción adicional')),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de orden')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='consultas.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['tipo_examen'],
                'indexes': [models.Index(fields=['tipo_examen'], name='consultas_e_tipo_ex_267954_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['-fecha_consulta'], name='consultas_c_fecha_c_c19ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['veterinario'], name='consultas_c_veterin_929b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['mascota'], name='consultas_c_mascota_d1f96d_idx'),
        ),
    ]
