# Generated by Django 4.2.7 on 2025-11-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(help_text='Veterinario que atiende la consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendidas', to='usuarios.veterinario', verbose_name='Veterinario'),
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['medicamento'], name='consultas_p_medicam_3fc8de_idx'),
        ),
        migrations.AddIndex(
            model_name='prescripcion',
            index=models.Index(fields=['-fecha_prescripcion'], name='consultas_p_fecha_p_71895e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialvacuna',
            index=models.Index(fields=['-fecha_registro'], name='consultas_h_fecha_r_2c65e0_idx'),
        ),
        migrations.AddIndex(
            model_name='historialvacuna',
            index=models.Index(fields=['estado'], name='consultas_h_estado_18fa04_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['mascota'], name='consultas_h_mascota_f49683_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['-fecha_actualizacion'], name='consultas_h_fecha_a_747a28_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['tipo_examen'], name='consultas_e_tipo_ex_267954_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['-fecha_consulta'], name='consultas_c_fecha_c_c19ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['veterinario'], name='consultas_c_veterin_929b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['mascota'], name='consultas_c_mascota_d1f96d_idx'),
        ),
    ]
