# Generated by Django 5.2.7 on 2025-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='notas_adicionales',
            field=models.TextField(blank=True, default='', help_text='Recomendaciones o seguimiento', verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Detalles específicos del examen a realizar', verbose_name='Descripción adicional'),
        ),
        migrations.AlterField(
            model_name='historialvacuna',
            name='vacunas_descripcion',
            field=models.TextField(blank=True, default='', help_text='Ej: Rabia, Parvovirus, Moquillo. Campo obligatorio si estado != AL_DIA', verbose_name='Vacunas pendientes/aplicadas'),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='indicaciones',
            field=models.TextField(blank=True, default='', help_text='Ej: Tomar 1 tableta cada 8 horas durante 7 días', verbose_name='Indicaciones de uso'),
        ),
    ]
