# Generated by Django 5.2.7 on 2025-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_notas_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado_vacunacion_actual',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], default='', help_text='Se actualiza automáticamente con cada consulta', max_length=20, verbose_name='Estado de vacunación actual'),
        ),
    ]
