# Generated by Django 4.2.7 on 2025-11-16 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_delete_historiaclinica'),
        ('inventario', '0002_alter_categoria_color_alter_kardex_detalle_and_more'),
        ('usuarios', '0001_initial'),
        ('consultas', '0004_alter_historiaclinica_estado_vacunacion_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='consentimiento_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Consentimiento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='consentimiento_otorgado',
            field=models.BooleanField(default=False, verbose_name='Consentimiento Otorgado'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='consentimiento_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Token de Consentimiento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='descripcion_consulta',
            field=models.TextField(verbose_name='Descripción de la consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='notas_adicionales',
            field=models.TextField(blank=True, default='', verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendidas', to='usuarios.veterinario', verbose_name='Veterinario'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción adicional'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado_vacunacion_actual',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], default='', max_length=20, verbose_name='Estado de vacunación actual'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historias_consulta', to='mascotas.mascota', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='historialvacuna',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='consultas.consulta', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='historialvacuna',
            name='estado',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('NINGUNA', 'Ninguna')], max_length=20, verbose_name='Estado de vacunación'),
        ),
        migrations.AlterField(
            model_name='historialvacuna',
            name='vacunas_descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Vacunas pendientes/aplicadas'),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='indicaciones',
            field=models.TextField(blank=True, default='', verbose_name='Indicaciones de uso'),
        ),
        migrations.AlterField(
            model_name='prescripcion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='inventario.producto', verbose_name='Medicamento'),
        ),
    ]
