# Generated by Django 4.2.7 on 2025-11-16 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0003_delete_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='AGENDADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.servicio')),
                ('veterinario', models.ForeignKey(limit_choices_to=models.Q(('usuario_roles__rol__nombre', 'veterinario'), ('usuario_roles__rol__nombre', 'practicante'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_como_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
