# Generated by Django 5.2.7 on 2025-11-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_kardex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='estado',
        ),
        migrations.AddField(
            model_name='kardex',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20),
        ),
    ]
