# Generated by Django 5.2.7 on 2025-11-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_kardex_estado_kardex_anulado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='anulado',
        ),
    ]
